### ISSUE TITLE
Math Equation Support

### ISSUE THREAD

**Issue by PenceP** [igormironchik/md-editor#1]
I see md4qt supports Latex math injections.
I didn't get these to work, but I was wondering if you had any plans to support 
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

**Comment by igormironchik** [comment]
Hello.

Done in 93de6b03a127d89125067e3cb1af8f3991a90d26.

Thanks for pointing me for missing feature.
